ssi-dk/diseasy

.Rbuildignore
cran-comments.md

fixes `usethis::use_cran_comments()` #9

docs: use cran_comments

---

.github/workflows/R-CMD-check.yaml
.github/workflows/check-no-suggests.yaml

This PR adds R-CMD-checks to the github workflows

feat: add R-CMD-check workflows

---

.github/workflows/R-CMD-check.yaml
.github/workflows/check-no-suggests.yaml
.github/workflows/test-coverage.yaml

This PR introduces a workaround to an existing `vroom` issue when using `RSQLite`
Build `RSQLite` from source
Introduces robustness issues. 
The PR should be reverted once `vroom` or `RSQLite` has a fix

chore: vroom_() workaround: compile RSQLite from source

---

R/0_R6_utils.R

This PR fixes windows issues with printr and adds the option to dynamically add linebreaks according to a max print width
The default file is changed from "/dev/null" to `nullfile()` -- fixes windows issue
A `max_width` argument is added. If string width exceeds `max_width`, we iteratively insert newlines
at breakpoints (" ") until each segment is either single words or shorter than `max_width`.
N/A

Improve and fix printr

---

tests/testthat/test-DiseasyActivity.R

This PR is part of the re-factoring of PR #30 which got too large due to scope-creep.
I am breaking that PR up into smaller chunks to make reviewing easier.
This PR does the following:
* Tests are made more specific
* Tests are updated to follow the best practice of having value before expectation
N/A
N/A

test(DiseasyActivity): improve tests

---

R/DiseasyActivity.R

This PR is part of the re-factoring of PR #30 which got too large due to scope-creep.
I am breaking that PR up into smaller chunks to make reviewing easier.
This PR does the following:
* Ensures `$get_scenario_activities()` always returns a `list`
* Ensures `$scenario_matrix` is still a `matrix` if only one scenario is loaded
N/A
N/A

feat(DiseasyActivity): improve type consistency for scenarios

---

inst/WORDLIST
vignettes/diseasy-activity.Rmd

This PR is part of the re-factoring of PR #30 which got too large due to scope-creep.
I am breaking that PR up into smaller chunks to make reviewing easier.
This PR adds a vignette describing the functionality of the module
N/A
N/A

docs(DiseasyActivity): add a vignette

---

R/DiseasyActivity.R

This PR is part of the re-factoring of PR #30 which got too large due to scope-creep.
I am breaking that PR up into smaller chunks to make reviewing easier.
This PR does the following:
1) Improves the `$describe()` method
2) Improves the printing of the `$scenario_matrix`
3) Rewrites the `add_activities` method
1) `$describe()` is improved by adding context text around the printing of `$scenario_matrix` and `$contact_basis$description`
2) `$scenario_matrix` printing is improved by converting it to a `data.frame`. This way, the attribute `secret_hash` is still there for hashing purposes but is not printed by R.
3) `$add_activities` is rewritten with code comments added.
N/A

feat(DiseasyActivity): improve `$describe()`, `$scenario_matrix`, and `$add_activities()`

---

R/DiseasyBaseModule.R
man/DiseasyBaseModule.Rd

Fixes parts of #37 
Description added to `DiseasyBaseModule`
TODO regarding ´update_logger´ removed
N/A

docs(DiseasyBaseModule): add description

---

R/DiseasyBaseModule.R
R/DiseasyObservables.R
man/DiseasyBaseModule.Rd
man/DiseasyObservables.Rd
vignettes/diseasy-observables.Rmd

This PR does a number of things
1) it improves the roxygen documentation for `DiseasyObservables` (Fixes parts of #37)
2) It adds a vignette that describes its basic principles (Fixes #42)
3) It adds a toggle to `DiseasyBaseModule` that gives control of logging (Fixes #46)
1) N/A
2) N/A
3) `DiseasyBaseModule` gets a `logging` argument and `options("diseasy.logging" = FALSE)`

Improved documentation to DiseasyObservables

---

R/DiseasySeason.R

Fixes #72  
Reformatted the anonymous functions such the updated `brace_linter` no longer triggers on the code
N/A

chore(DiseasySeason): reformat anonymous functions

---

DESCRIPTION
_pkgdown.yml

Fixes #55
This PR ensures that Statens Serum Institut is attributed as a copyright holder and funder of this project. Moreover, it creates a clickable SSI logo for the pkgdown site, that redirects to [SSI](https://www.ssi.dk/). See e.g. the [aedseo](https://ssi-dk.github.io/aedseo/) site.
Modified your `DESCRIPTION` file to include another "person":
`person("Statens Serum Institut, SSI", role = c("cph", "fnd")`
Modified your `_pkgdown.yml` file to include the following lines of code:
```
authors:
Statens Serum Institut, SSI:
href: https://www.ssi.dk/
html: >-
```

Add SSI as copyright holder

---

DESCRIPTION
R/DiseasyObservables.R
data-raw/contact_basis.R
man/DiseasyObservables.Rd
tests/testthat/test-DiseasyObservables.R
tests/testthat/test-DiseasySeason.R
vignettes/diseasy-observables.Rmd

This PR fixes R-CMD-Check errors when suggested packages are not installed.
The evaluation of the vignettes is made conditional on the installation of the required suggests packages.
The test are still failing (with warnings, not errors) due to a waning about deprecated `check_from` argument in `dbplyr`.
This will be fixed with the next release of diseasystore: 
The tests for `DiseasySeason` and `DiseasyObservables` are failing.
This is due to the tests being run across all `diseasystores` which as introduced errors.
This is being fixed in a different PR:
The tests for `get_scenario_openness` failing.
This seems to be due to a change in the `test_that` comparrisons.
This is being fixed in a different PR:

Gracefeully handle missing suggests

---

R/0_R6_utils.R
R/0_linters.R
R/DiseasyActivity.R
R/DiseasyBaseModule.R
R/DiseasySeason.R
pak.lock
tests/spelling.R
tests/testthat/helper-setup.R
tests/testthat/test-DiseasyActivity.R
tests/testthat/test-DiseasyBaseModule.R
tests/testthat/test-DiseasyObservables.R
tests/testthat/test-DiseasySeason.R

This PR introduces a few minor fixes.
1) Tests that look compare with `NULL` now uses the existence aware `%.%` operator
Presently, we will not capture unintended API changes with how `$` works.
2) `rlang::is_installed()` is now preferred over `requireNamespace`
3) Some missing punctuation is added
4) Test labels improved - and two tests swapped in the file 
5) A failing test expectation is updated from `list()` to `named list()`
6) `purrr::imap` is used instead of `purrr::map2` when needed to use names in the loop.
7) Improve the error messages of `parse_diseasyconn()`
N/A
~~The tests for `DiseasySeason` and `DiseasyObservables` are failing.~~
~~This is due to the tests being run across all `diseasystores` which as introduced errors.~~
~~This is being fixed in a different PR:~~
~~The …

Various minor fixes

---

R/DiseasySeason.R
pak.lock

fix(cosine_season): Store peak value in dots

---

R/DiseasySeason.R
tests/testthat/test-DiseasyActivity.R
tests/testthat/test-DiseasyObservables.R
tests/testthat/test-DiseasySeason.R

This PR adds tests for the `$describe()` functions in the functional modules.
Much of our missing test-coverage stems from lack of tests for `$describe()` functions, so this should 
improve our test coverage to better reflect the broad testing that we do.
Tests were added to check that `$describe()` could run without error as the module gets configured.
These tests don't check the output of `$describe()` but only ensures that the functions can run.
Also, while editing `test-DiseasyObservables` I noticed that the module was sometimes called `m` instead of `obs`. I changed this to align with the rest of the file (and the other test files)
N/A

Add tests for `$describe()`

---

data-raw/contact_basis.R

The checks of installation status in `contact_basis.R` was unnecessarily complex.
This PR fixes this
N/A
N/A

Simplify `contact_basis` package requirement checks

---

.lintr_exclusions.R
DESCRIPTION
R/0_R6_utils.R
R/0_hypoexponential.R
R/0_linters.R
R/DiseasyActivity.R
R/DiseasyBaseModule.R
R/DiseasyModel.R
R/DiseasyModelOde.R
R/DiseasyModelOdeSeir.R
R/DiseasyObservables.R
R/DiseasySeason.R
data-raw/dk_activity_units.R
pak.lock
tests/testthat/helper-setup.R
tests/testthat/setup.R
tests/testthat/test-0_rd_files.R
tests/testthat/test-DiseasyVariant.R
vignettes/diseasy-activity.Rmd
vignettes/diseasy-observables.Rmd
vignettes/diseasy-variant.Rmd
vignettes/diseasy.Rmd

A recent update to `lintr` introduce new linters that are not compatible with the diseasy style guide
This PR disables these and fixes remaining lints
N/A
N/A

Update the list of linters after lintr v3.2

---

R/DiseasyBaseModule.R
R/DiseasyObservables.R
man/Diseasy-BRM-models.Rd
man/Diseasy-GLM-models.Rd
man/DiseasyActivity.Rd
man/DiseasyBaseModule.Rd
man/DiseasyModel.Rd
man/DiseasyModelOde.Rd
man/DiseasyModelOdeSeir.Rd
man/DiseasyModelRegression.Rd
man/DiseasyObservables.Rd
man/DiseasySeason.Rd
man/DiseasyVariant.Rd

As of R6 v2.4.0, `finalize()` methods needs to be private which breaks our implementation.
This PR removes the generic `finalize` and lets R6 handle clean up 
N/A
N/A

chore(DiseasyBaseModule): Remove `finalize` private method

---

tests/testthat/test-0_R6_utils.R
tests/testthat/test-hash_environment.R

As of 70130ac893b49f32bcba07129442e51057068f7d, the `hash_environment()` was moved to its own file but its tests were not, which leads to issues when synchronising files across repos
Tests moved to seperate file
N/A

Move `hash_environment` tests to separate file
